// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgPjubI29xLkXPLTxYqkOL9eE-oD-zhfM',
    appId: '1:894786792455:web:29d908dcc9c4346a3ecea2',
    messagingSenderId: '894786792455',
    projectId: 'aca-project-5e2af',
    authDomain: 'aca-project-5e2af.firebaseapp.com',
    storageBucket: 'aca-project-5e2af.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1-Z8O1dkJJEDotk-VWpeCI3QDLPDk8lM',
    appId: '1:894786792455:android:ec6a09a4f870fe9c3ecea2',
    messagingSenderId: '894786792455',
    projectId: 'aca-project-5e2af',
    storageBucket: 'aca-project-5e2af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmesjg0zNx23N3aL8vPlhTbI-wHHZ4nCo',
    appId: '1:894786792455:ios:dee3bd0c3b1ac8393ecea2',
    messagingSenderId: '894786792455',
    projectId: 'aca-project-5e2af',
    storageBucket: 'aca-project-5e2af.firebasestorage.app',
    iosBundleId: 'com.example.acaProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmesjg0zNx23N3aL8vPlhTbI-wHHZ4nCo',
    appId: '1:894786792455:ios:dee3bd0c3b1ac8393ecea2',
    messagingSenderId: '894786792455',
    projectId: 'aca-project-5e2af',
    storageBucket: 'aca-project-5e2af.firebasestorage.app',
    iosBundleId: 'com.example.acaProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgPjubI29xLkXPLTxYqkOL9eE-oD-zhfM',
    appId: '1:894786792455:web:8fa0ef9ad2af3af93ecea2',
    messagingSenderId: '894786792455',
    projectId: 'aca-project-5e2af',
    authDomain: 'aca-project-5e2af.firebaseapp.com',
    storageBucket: 'aca-project-5e2af.firebasestorage.app',
  );
}
